apiVersion: v1
kind: DeploymentConfig
metadata:
    name: inventory-service
spec:
  template:
    spec:
      containers:
        - env:
          - name: JAEGER_SERVER_HOSTNAME
            value: jaeger-agent.cockpit.svc.cluster.local
